Repository ebchoi/chart-and-board, pull requests merged in 2022-10, with the labels that each got.

#5 Edit: 메인 컨텐츠 레이아웃의 공통 패딩 적용
  .prettierrc
  src/Router.js
  src/containers/Layout.container.js
Labels: enhancement

#4 Add:게시판 페이지네이션,세션스토리지저장후 데이터 사용기능 구현
  public/data/board-data.json
  src/pages/Board.pages.js
  src/styles/Theme.js
Labels: good first issue

#10 Add: Line, Pie, Bar 차트 만들기 & 이미지 저장 기능 구현
  package-lock.json
  package.json
  public/data/graph-data.json
  src/components/AgeRangeChart.components.js
  src/components/MonthlyPostsChart.components.js
  src/components/MonthlyVisitorChart.components.js
  src/components/_index.components.js
  src/pages/Main.pages.js
  src/pages/Post.pages.js
Labels: documentation
